### ISSUE TITLE
GeoWave 0.95 on Ubuntu 16.04: java.lang.UnsupportedOperationException: GeoTools raster files cannot be ingested using intermediate avro files

### ISSUE THREAD

**Issue by neelchauhan** [locationtech/geowave#1187]
When I run the following command on a Ubuntu 16.04 laptop:

    geowave ingest localToHdfs shape.shx localhost:9000 /data

I get an error like this:

    04 Oct 14:44:47 WARN [local.LocalFileIngestDriver] - Plugin provider for ingest type 'geotools-raster' does not support avro ingest
    java.lang.UnsupportedOperationException: GeoTools raster files cannot be ingested using intermediate avro files
            at mil.nga.giat.geowave.format.geotools.raster.GeoToolsRasterDataStoreIngestFormat.createAvroFormatPlugin(GeoToolsRasterDataStoreIngestFormat.java:36)
            at mil.nga.giat.geowave.core.ingest.operations.options.IngestFormatPluginOptions.createAvroPlugins(IngestFormatPluginOptions.java:159)
            at mil.nga.giat.geowave.core.ingest.operations.LocalToHdfsCommand.execute(LocalToHdfsCommand.java:82)
            at mil.nga.giat.geowave.core.cli.GeoWaveMain.run(GeoWaveMain.java:87)
            at mil.nga.giat.geowave.core.cli.GeoWaveMain.main(GeoWaveMain.java:53)

I had this error on GeoWave 0.95 and with both the provided JAR file and my own compiled version. What could be going on?

**Comment by rfecher** [comment]
To ingest shapefiles, use the .shp file rather than the supplemental .shx file.

Also, because geotools shapefile reader does not support HDFS protocol, use `localToGW` instead of `localToHdfs`.  Lastly, to be explicit on the file format you can supply ` -f geotools-vector` on the commandline.  Let us know if problems persist.

**Comment by neelchauhan** [comment]
Sorry if I am late, but thank you so much for your help.

Also, if I try to ingest a shapefile with `localToGW`, I get an error like:

    Unable to execute operation: Cannot find index(s) by name: 316000.0,234000.0,316001.851,234002.302

I know the arguments are like:

    geowave ingest localToGW [options] <file or directory> <storename> <comma delimited index/group list>

But the question is, what is the `<comma delimited index/group list>`? Searching the Internet did not yield anything related to this.

**Comment by rfecher** [comment]
`<comma delimited index/group list>` is merely referring to a named configuration (or multiple) that references how you want to index the data on ingest. Each "index" results in a table within your key-value store.  So `geowave config addindex ...` is a typical precursor to ingest, as in the case of this set of commands from the quickstart guide:
http://locationtech.github.io/geowave/quickstart.html#config-and-ingest

We also bundle default configurations in case you really don't want to define your own (such as `default-spatial` or `default-spatial-temporal`).  It looks to me like you used `316000.0,234000.0,316001.851,234002.302` in your commandline params, where it should be replaced by a named index configuration (for instance `default-spatial`)

**Comment by kullaibigdata** [comment]
Hi rfecher,

I read your answers and I resolve some of the issue but this time I didn't identify could you please help to solve this issue.

[root@mapr1 ~]# geowave gs addds -ds geowave_eea -ws geowave eea-demo
16 Sep 04:49:06 WARN [cli.GeoWaveMain] - Unable to execute operation
javax.ws.rs.ProcessingException: java.net.SocketException: Unexpected end of file from server
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
        at mil.nga.giat.geowave.cli.geoserver.GeoServerRestClient.addDatastore(GeoServerRestClient.java:823)
        at mil.nga.giat.geowave.cli.geoserver.GeoServerAddDatastoreCommand.computeResults(GeoServerAddDatastoreCommand.java:77)
        at mil.nga.giat.geowave.cli.geoserver.GeoServerAddDatastoreCommand.execute(GeoServerAddDatastoreCommand.java:59)
        at mil.nga.giat.geowave.core.cli.GeoWaveMain.run(GeoWaveMain.java:87)
        at mil.nga.giat.geowave.core.cli.GeoWaveMain.main(GeoWaveMain.java:53)
Caused by: java.net.SocketException: Unexpected end of file from server
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
        ... 15 more
Usage: geowave gs addds [options] <GeoWave store name>
  Options:
    -ds, --datastore
       datastore name
       Default: geowave_eea
    -ws, --workspace
       workspace name
       Default: geowave

Unable to execute operation: java.net.SocketException: Unexpected end of file from server


Thanks,
Kullai.

**Comment by rfecher** [comment]
this references outdated versions.
