### ISSUE TITLE
ingest failed

### ISSUE THREAD

**Issue by scially** [locationtech/geowave#1605]
I get an error when I ingest a shp by geowave
```
geowave.sh config addindex -t spatial -np 4 -ps HASH gw-spatial
geowave.sh config addstore -t redis -a redis://127.0.0.1:6379 --gwNamespace redis gw-redis
geowave.sh ingest localtogw -f geotools-vector ./SDDLTB.shp  gw-redis gw-spatial
```
Property sheet
![image](https://user-images.githubusercontent.com/22127608/62437198-d3dbd680-b774-11e9-981f-4e15156c80bc.png)

```
05 八月 11:26:24 ERROR [ingest.AbstractLocalFileIngestDriver] - Fatal error occured while trying write to an index writer.
java.lang.NullPointerException
        at org.locationtech.geowave.core.store.data.CommonIndexedPersistenceEncoding.getInsertionIds(CommonIndexedPersistenceEncoding.java:67)
        at org.locationtech.geowave.core.store.base.BaseDataStoreUtils.getWriteInfo(BaseDataStoreUtils.java:348)
        at org.locationtech.geowave.core.store.base.BaseIndexWriter.write(BaseIndexWriter.java:77)
        at org.locationtech.geowave.core.store.base.BaseIndexWriter.write(BaseIndexWriter.java:64)
        at org.locationtech.geowave.core.store.index.writer.IndexCompositeWriter.lambda$write$0(IndexCompositeWriter.java:42)
        at org.locationtech.geowave.core.store.index.writer.IndexCompositeWriter.internalWrite(IndexCompositeWriter.java:55)
        at org.locationtech.geowave.core.store.index.writer.IndexCompositeWriter.write(IndexCompositeWriter.java:42)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.write(AbstractLocalFileIngestDriver.java:293)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.ingestData(AbstractLocalFileIngestDriver.java:280)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.processFileSingleThreaded(AbstractLocalFileIngestDriver.java:208)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.processFile(AbstractLocalFileIngestDriver.java:153)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.processFile(AbstractLocalFileIngestDriver.java:38)
        at org.locationtech.geowave.core.store.ingest.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:128)
        at org.locationtech.geowave.core.store.ingest.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:36)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileDriver.processInput(AbstractLocalFileDriver.java:125)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.runOperation(AbstractLocalFileIngestDriver.java:72)
        at org.locationtech.geowave.core.ingest.operations.LocalToGeowaveCommand.computeResults(LocalToGeowaveCommand.java:176)
        at org.locationtech.geowave.core.ingest.operations.LocalToGeowaveCommand.execute(LocalToGeowaveCommand.java:72)
        at org.locationtech.geowave.core.cli.GeoWaveMain.run(GeoWaveMain.java:70)
        at org.locationtech.geowave.core.cli.GeoWaveMain.main(GeoWaveMain.java:41)
05 八月 11:26:24 WARN [cli.GeoWaveMain] - Unable to execute operation
java.lang.RuntimeException: Interrupted ingesting GeoWaveData
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.processFileSingleThreaded(AbstractLocalFileIngestDriver.java:219)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.processFile(AbstractLocalFileIngestDriver.java:153)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.processFile(AbstractLocalFileIngestDriver.java:38)
        at org.locationtech.geowave.core.store.ingest.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:128)
        at org.locationtech.geowave.core.store.ingest.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:36)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileDriver.processInput(AbstractLocalFileDriver.java:125)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.runOperation(AbstractLocalFileIngestDriver.java:72)
        at org.locationtech.geowave.core.ingest.operations.LocalToGeowaveCommand.computeResults(LocalToGeowaveCommand.java:176)
        at org.locationtech.geowave.core.ingest.operations.LocalToGeowaveCommand.execute(LocalToGeowaveCommand.java:72)
        at org.locationtech.geowave.core.cli.GeoWaveMain.run(GeoWaveMain.java:70)
        at org.locationtech.geowave.core.cli.GeoWaveMain.main(GeoWaveMain.java:41)
Caused by: java.lang.RuntimeException: Fatal error occured while trying write to an index writer.
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.ingestData(AbstractLocalFileIngestDriver.java:288)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.processFileSingleThreaded(AbstractLocalFileIngestDriver.java:208)
        ... 12 more
Caused by: java.lang.NullPointerException
        at org.locationtech.geowave.core.store.data.CommonIndexedPersistenceEncoding.getInsertionIds(CommonIndexedPersistenceEncoding.java:67)
        at org.locationtech.geowave.core.store.base.BaseDataStoreUtils.getWriteInfo(BaseDataStoreUtils.java:348)
        at org.locationtech.geowave.core.store.base.BaseIndexWriter.write(BaseIndexWriter.java:77)
        at org.locationtech.geowave.core.store.base.BaseIndexWriter.write(BaseIndexWriter.java:64)
        at org.locationtech.geowave.core.store.index.writer.IndexCompositeWriter.lambda$write$0(IndexCompositeWriter.java:42)
        at org.locationtech.geowave.core.store.index.writer.IndexCompositeWriter.internalWrite(IndexCompositeWriter.java:55)
        at org.locationtech.geowave.core.store.index.writer.IndexCompositeWriter.write(IndexCompositeWriter.java:42)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.write(AbstractLocalFileIngestDriver.java:293)
        at org.locationtech.geowave.core.store.ingest.AbstractLocalFileIngestDriver.ingestData(AbstractLocalFileIngestDriver.java:280)
        ... 13 more
Usage: geowave ingest localToGW [options] <file or directory> <storename> <comma delimited index/group list>
```

**Comment by rfecher** [comment]
it may help to see an example of this data. my guess is it looks like it can't get the geometry for at least one of the rows but I'm not sure why that would be.

**Comment by scially** [comment]
![image](https://user-images.githubusercontent.com/22127608/62504930-309ac800-b82d-11e9-9f2f-68233a869946.png)

thanks...  i read the shp by geotools, and find a attribute that doesn't have geometry
