### ISSUE TITLE
Raster Demo - GDAL native libraries are not available

### ISSUE THREAD

**Issue by pfrollo** [locationtech/geowave#1649]
I follow the [raster demo](https://locationtech.github.io/geowave/walkthrough-raster.html) instructions and when I execute the ingestion command 
`
geowave util landsat ingest --nbestperspatial --nbestscenes 1 --usecachedscenes --cql "$BERLIN_BBOX AND band='B8' AND cloudCover>0" --crop --retainimages -ws /Users/work/dev/data/rasterDemo/landsat/ --vectorstore landsatvector --pyramid --coverage berlin_mosaic  landsatraster spatial
` 
I get this error:
```
26 Dec 14:20:14 WARN [cli.GeoWaveMain] - Unable to execute operation
java.lang.IllegalStateException: GDAL native libraries are not available.
	at it.geosolutions.imageio.gdalframework.GDALImageReader.setInput(GDALImageReader.java:636)
	at javax.imageio.ImageReader.setInput(ImageReader.java:380)
	at org.geotools.coverageio.BaseGridCoverage2DReader.<init>(BaseGridCoverage2DReader.java:164)
	at org.geotools.coverageio.gdal.BaseGDALGridCoverage2DReader.<init>(BaseGDALGridCoverage2DReader.java:77)
	at org.locationtech.geowave.adapter.raster.plugin.gdal.GDALGeoTiffReader.<init>(GDALGeoTiffReader.java:40)
	at org.locationtech.geowave.adapter.raster.plugin.gdal.GDALGeoTiffReader.<init>(GDALGeoTiffReader.java:29)
	at org.locationtech.geowave.format.landsat8.RasterIngestRunner.getBandData(RasterIngestRunner.java:151)
	at org.locationtech.geowave.format.landsat8.RasterIngestRunner.processPreviousScene(RasterIngestRunner.java:339)
	at org.locationtech.geowave.format.landsat8.RasterIngestRunner.nextScene(RasterIngestRunner.java:321)
	at org.locationtech.geowave.format.landsat8.IngestRunner.nextScene(IngestRunner.java:100)
	at org.locationtech.geowave.format.landsat8.AnalyzeRunner.runInternal(AnalyzeRunner.java:55)
	at org.locationtech.geowave.format.landsat8.RasterIngestRunner.runInternal(RasterIngestRunner.java:128)
	at org.locationtech.geowave.format.landsat8.IngestRunner.runInternal(IngestRunner.java:106)
	at org.locationtech.geowave.format.landsat8.Landsat8IngestCommand.execute(Landsat8IngestCommand.java:57)
	at org.locationtech.geowave.core.cli.GeoWaveMain.run(GeoWaveMain.java:70)
	at org.locationtech.geowave.core.cli.GeoWaveMain.main(GeoWaveMain.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:62)
```

**Comment by jdgarrett** [comment]
What platform are you using?  The raster demo has instructions for installing the GDAL native libraries at https://locationtech.github.io/geowave/walkthrough-raster.html#download-and-unpack-the-gdal-library.  These libraries are not available for Mac, but should work for Linux and Windows.

**Comment by pfrollo** [comment]
I am on Mac. Would it be useful to mention in the documentation that the libs are not available for Mac and as a result it is not possible to do Raster Demo on Mac?

**Comment by jdgarrett** [comment]
The updated documentation states that the raster demo does not work on Mac.  I have added issue #1684 for finding a solution for getting this to work on Mac in the future.

**Comment by jdgarrett** [comment]
This issue has now been resolved and the updated `geowave raster installgdal` command will be be part of the 1.2 release.
