### ISSUE TITLE
Exception attempting to read userData.json

### ISSUE THREAD

**Issue by michaeljfazio** [locationtech/geowave#1728]
I'm running HBase on EMR backed by S3. When ingesting data, the following exception is always thrown at some point. It doesn't seem to cause an issue, the data still imports correctly as far as I can tell.

```bash
20/05/19 08:59:27 INFO HBaseAdmin: Started disable of geowave.sar_GEOWAVE_METADATA
20/05/19 08:59:32 ERROR UserData: Error encountered while try to get user data
java.io.IOException: File '/var/aws/emr/userData.json' cannot be read
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:296)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
        at com.amazon.ws.emr.hadoop.fs.util.UserData.getUserData(UserData.java:62)
        at com.amazon.ws.emr.hadoop.fs.util.UserData.<init>(UserData.java:39)
        at com.amazon.ws.emr.hadoop.fs.util.UserData.ofDefaultResourceLocations(UserData.java:52)
        at com.amazon.ws.emr.hadoop.fs.util.AWSSessionCredentialsProviderFactory.buildSTSClient(AWSSessionCredentialsProviderFactory.java:52)
        at com.amazon.ws.emr.hadoop.fs.util.AWSSessionCredentialsProviderFactory.<clinit>(AWSSessionCredentialsProviderFactory.java:17)
        at com.amazon.ws.emr.hadoop.fs.guice.UserGroupMappingAWSSessionCredentialsProvider.getCredentials(UserGroupMappingAWSSessionCredentialsProvider.java:56)
        at com.amazon.ws.emr.hadoop.fs.guice.UserGroupMappingAWSSessionCredentialsProvider.getCredentials(UserGroupMappingAWSSessionCredentialsProvider.java:15)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1225)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:801)
```

**Comment by heisenbergye** [comment]
this issue needs to grive read-only privilege for others in all nodes
```
sudo chmod 444 /var/aws/emr/userData.json
```
default is 440
