### ISSUE TITLE
GeoWaveStoreFinder is not an ImageIO SPI class

### ISSUE THREAD

**Issue by YaseminAkyuz** [locationtech/geowave#1749]
I'm just getting started with Geowave and Cassandra.
 I'm trying to add a data store using following cli command: 
       geowave store add --gwNamespace geowave.gdelt -t cassandra --contactPoints 127.0.0.1:9160. 
I'm getting error and could not find a solution. 

Error: java.lang.ExceptionInInitializerError
at org.locationtech.geowave.core.store.cli.store.DataStorePluginOptions.selectPlugin(DataStorePluginOptions.java:72)
at org.locationtech.geowave.core.store.cli.store.AddStoreCommand.prepare(AddStoreCommand.java:60)
at org.locationtech.geowave.core.cli.parser.OperationParser.parseInternal(OperationParser.java:94)
at org.locationtech.geowave.core.cli.parser.OperationParser.parse(OperationParser.java:65)
at org.locationtech.geowave.core.cli.GeoWaveMain.main(GeoWaveMain.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.lang.IllegalArgumentException: org.locationtech.geowave.core.store.GeoWaveStoreFinder is not an ImageIO SPI class
at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)
at org.locationtech.geowave.core.index.SPIServiceRegistry.<init>(SPIServiceRegistry.java:42)
at org.locationtech.geowave.core.store.GeoWaveStoreFinder.getRegisteredFactories(GeoWaveStoreFinder.java:326)
at org.locationtech.geowave.core.store.GeoWaveStoreFinder.getRegisteredStoreFactoryFamilies(GeoWaveStoreFinder.java:281)
at org.locationtech.geowave.core.store.GeoWaveStoreFinder.getStoreNames(GeoWaveStoreFinder.java:229)
at org.locationtech.geowave.core.store.GeoWaveStoreFinder.<clinit>(GeoWaveStoreFinder.java:40)

**Comment by rfecher** [comment]
curreently GeoWave supports Java8 ... it was confirmed the user was mistakenly using Java 13 and received this on the commandline.  For anyone sees this error, ensure you're using java 8.
