### ISSUE TITLE
KDE MR Job, ClassCastException on subsequent runs

### ISSUE THREAD

**Issue by ewilson-radblue** [locationtech/geowave#478]
I was trying to reproduce the capability demonstrated by KDERasterResizeIT.java and ran the KDE job multiple times.  The result on the runs after the first was the following ClassCastException:

```
Error: java.lang.ClassCastException: org.geotools.coverage.grid.GridCoverage2D cannot be cast to org.opengis.feature.simple.SimpleFeature
    at mil.nga.giat.geowave.analytic.mapreduce.kde.GaussianCellMapper.map(GaussianCellMapper.java:22)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:784)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

I'm not sure if I'm running something incorrectly.  I ran it using the analytics-singlejar, building it using the Maven package command as described in the documentation.  The commands ran were the following:

```
java -cp geowave-analytic-mapreduce-0.8.9-SNAPSHOT-analytics-singlejar.jar mil.nga.giat.geowave.analytic.mapreduce.kde.KDEJobRunner master.node:2181 accumulo geowave geowave geowave.heatmap Default 15 17 2 4 heatmap0 hdfs://master.node:9000 master.node:8032 geowave.heatmap 1
java -cp geowave-analytic-mapreduce-0.8.9-SNAPSHOT-analytics-singlejar.jar mil.nga.giat.geowave.analytic.mapreduce.kde.KDEJobRunner master.node:2181 accumulo geowave geowave geowave.heatmap Default 13 15 2 4 heatmap2 hdfs://master.node:9000 master.node:8032 geowave.heatmap 4
java -cp geowave-analytic-mapreduce-0.8.9-SNAPSHOT-analytics-singlejar.jar mil.nga.giat.geowave.analytic.mapreduce.kde.KDEJobRunner master.node:2181 accumulo geowave geowave geowave.heatmap Default 11 13 2 4 heatmap4 hdfs://master.node:9000 master.node:8032 geowave.heatmap 16
java -cp geowave-analytic-mapreduce-0.8.9-SNAPSHOT-analytics-singlejar.jar mil.nga.giat.geowave.analytic.mapreduce.kde.KDEJobRunner master.node:2181 accumulo geowave geowave geowave.heatmap Default  9 11 2 4 heatmap6 hdfs://master.node:9000 master.node:8032 geowave.heatmap 64
```

**Comment by ewilson-radblue** [comment]
Also, one change I had to make to get it to run in my set-up was to add the following to GeoWaveConfiguratorBase.setRemoteInvocationParams():

    conf.set("yarn.resourcemanager.scheduler.address", "master.node:8030");

I hard-coded it into the build I put together just to test with, but it may need to be passed in and set similarly to the "yarn.resourcemanager.address" value.
